#!/bin/bash

# Function to handle configuration updates
update_configs() {
    clear
    echo -e "${GREEN}--- Update Configuration Mode ---${NC}"
    
    # Check if any services exist to list them (optional enhancement)
    # ls /etc/systemd/system/*.service | grep -vE "dbus|syslog" ... too noisy
    
    local APP_CODE_NAME=""
    
    while true; do
        read -p "Enter the App Code Name to update (or 'q' to quit): " APP_CODE_NAME
        
        if [[ "$APP_CODE_NAME" =~ ^[Qq]$ ]]; then
            return
        fi

        if [ -z "$APP_CODE_NAME" ]; then
            echo -e "${RED}App Code Name cannot be empty.${NC}"
            continue
        fi
        
        # Check if the service file exists as a proxy for the app existing
        SERVICE_FILE="/etc/systemd/system/${APP_CODE_NAME}.service"
        
        if [ ! -f "$SERVICE_FILE" ]; then
             echo -e "${RED}Service file not found: $SERVICE_FILE${NC}"
             echo "Please check the App Code Name and try again."
             continue
        else
             echo -e "${GREEN}Found service for '$APP_CODE_NAME'.${NC}"
             break
        fi
    done

    while true; do
        echo -e "\n${CYAN}Update Menu for '$APP_CODE_NAME':${NC}"
        echo "1. Edit Systemd Service (CPU, Memory, Env Vars)"
        echo "2. Edit Nginx Configuration (Domain, Headers, SSL)"
        echo "3. Reload & Restart All Services"
        echo "4. Return to Main Menu"
        read -p "Select an option [1-4]: " UPDATE_CHOICE
        
        case $UPDATE_CHOICE in
            1)
                edit_systemd_config
                ;;
            2)
                edit_nginx_config
                ;;
            3)
                reload_services
                ;;
            4)
                break
                ;;
            *)
                echo -e "${RED}Invalid option.${NC}"
                ;;
        esac
    done
}

edit_systemd_config() {
    local service_file="/etc/systemd/system/$APP_CODE_NAME.service"
    
    echo -e "${YELLOW}Reading current configuration from Systemd service file...${NC}"
    
    # 1. Parse existing values
    # We use grep and cut to extract values. This assumes the format generated by this script.
    
    # Static values (preserve these)
    APP_NICE_NAME=$(grep "^Description=" "$service_file" | cut -d= -f2- | sed 's/ API Powered by FastAPI//')
    GITHUB_REPO=$(grep "^Documentation=" "$service_file" | cut -d= -f2-)
    APP_DIR=$(grep "^WorkingDirectory=" "$service_file" | cut -d= -f2-)
    
    # Tuning values (extract to offer as defaults)
    local current_port
    current_port=$(grep " --port " "$service_file" | awk '{print $2}')
    APP_PORT=${current_port:-8000}
    
    local current_workers
    current_workers=$(grep " --workers " "$service_file" | awk '{print $2}')
    
    local current_concurrency
    current_concurrency=$(grep " --limit-concurrency " "$service_file" | awk '{print $2}')
    
    local current_backlog
    current_backlog=$(grep " --backlog " "$service_file" | awk '{print $2}')
    
    local current_nice
    current_nice=$(grep "^Nice=" "$service_file" | cut -d= -f2-)
    
    local current_cpu_quota
    current_cpu_quota=$(grep "^CPUQuota=" "$service_file" | cut -d= -f2-)
    
    local current_memory_max
    current_memory_max=$(grep "^MemoryMax=" "$service_file" | cut -d= -f2-)
    
    # Extract Uvicorn App Module (Assumes it's the specific line pattern)
    # It tries to find the line that doesn't start with recognized flags in the ExecStart block?
    # Actually, in our template, it is the last argument.
    # We can try to grab the last line of the ExecStart block if we could multiline grep, but grep is line based.
    # Our generated file has "    $UVICORN_APP_MODULE" on a new line at the end of ExecStart.
    # Let's try to grab the line that matches the module pattern.
    UVICORN_APP_MODULE=$(grep -E "^    [a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*:[a-zA-Z_][a-zA-Z0-9_]*$" "$service_file" | head -n 1 | awk '{print $1}')
    if [ -z "$UVICORN_APP_MODULE" ]; then
         UVICORN_APP_MODULE="main:app" # Fallback
    fi

    # 2. Hardware Recommendations (Logic from previous step)
    local num_cores
    num_cores=$(nproc)
    local recommended_workers=$(($num_cores * 2 + 1))
    
    local TOTAL_MEM_MB
    TOTAL_MEM_MB=$(free -m | awk '/^Mem:/{print $2}' 2>/dev/null)
    if ! [[ "$TOTAL_MEM_MB" =~ ^[0-9]+$ ]] || [ -z "$TOTAL_MEM_MB" ]; then TOTAL_MEM_MB=1024; fi
    
    local RECOMMENDED_MEM_MAX_RAW=$((TOTAL_MEM_MB / 8))
    local RECOMMENDED_MEM_MAX_STR=""
    if [ "$RECOMMENDED_MEM_MAX_RAW" -lt 256 ]; then RECOMMENDED_MEM_MAX_STR="256M";
    elif [ "$RECOMMENDED_MEM_MAX_RAW" -gt 4096 ]; then RECOMMENDED_MEM_MAX_STR="4G";
    else RECOMMENDED_MEM_MAX_STR="${RECOMMENDED_MEM_MAX_RAW}M"; fi

    echo -e "\n${CYAN}--- Current Hardware & Config ---${NC}"
    echo -e "CPU Cores: ${YELLOW}$num_cores${NC}, RAM: ${YELLOW}${TOTAL_MEM_MB}MB${NC}"
    echo -e "Recommended Workers: ${GREEN}$recommended_workers${NC} (Current: $current_workers)"
    echo -e "Recommended MemoryMax: ${GREEN}$RECOMMENDED_MEM_MAX_STR${NC} (Current: $current_memory_max)"
    echo -e "${CYAN}---------------------------------${NC}"
    echo -e "${YELLOW}To keep the current/default value, just press Enter.${NC}\n"

    # 3. Prompt for new values

    # We use the 'get_input' function which should be available from the parent script execution context.
    # Note: We are setting global variables that create_systemd_service uses.
    
    get_input "Enter the number of Uvicorn workers" NUM_WORKERS validate_integer \
        "Enter the number of worker processes." "${current_workers:-$recommended_workers}"
        
    get_input "Enter Uvicorn concurrency limit" CONCURRENCY_LIMIT validate_integer \
        "Max concurrent connections per worker." "${current_concurrency:-1000}"
        
    get_input "Enter Uvicorn backlog size" BACKLOG_SIZE validate_integer \
        "Max incoming connection queue." "${current_backlog:-2048}"
        
    get_input "Enter systemd Nice value" NICE_VALUE validate_nice_value \
        "Process priority (-20 to 19)." "${current_nice:-0}"
        
    get_input "Enter systemd CPUQuota" CPU_QUOTA validate_percentage \
        "CPU limit (e.g. 80%, 200%)." "${current_cpu_quota:-80%}"
        
    get_input "Enter systemd MemoryMax" MEMORY_MAX "" \
        "Max RAM usage (e.g. 512M, 2G)." "${current_memory_max:-$RECOMMENDED_MEM_MAX_STR}"
        
    get_input "Enter Python module and FastAPI instance" UVICORN_APP_MODULE validate_python_module_instance_format \
        "Python module:instance." "$UVICORN_APP_MODULE"
        
    read -p "Do you want to apply these changes? (y/N): " APPLY_CHOICE
    if [[ "$APPLY_CHOICE" =~ ^[Yy]$ ]]; then
         # 4. Regenerate Config
         create_systemd_service # This function uses the globals we just set
         
         # Verification
         echo -e "${GREEN}Systemd configuration updated and service restarted.${NC}"
         sudo systemctl status "$APP_CODE_NAME" --no-pager | head -n 10
    else
         echo -e "${YELLOW}Changes discarded.${NC}"
    fi
}

edit_nginx_config() {
    local nginx_file="/etc/nginx/sites-available/$APP_CODE_NAME"
    if [ ! -f "$nginx_file" ]; then
         echo -e "${RED}Nginx config not found at $nginx_file.${NC}"
         return
    fi
    
    echo -e "${YELLOW}Reading current configuration from Nginx config file...${NC}"
    
    # 1. Parse existing values
    local current_domain
    current_domain=$(grep "server_name " "$nginx_file" | awk '{print $2}' | sed 's/;//')
    DOMAIN_NAME=${current_domain:-}
    
    local current_port
    current_port=$(grep "server 127.0.0.1:" "$nginx_file" | head -n 1 | awk -F: '{print $2}' | sed 's/;//')
    APP_PORT=${current_port:-8000}
    
    local current_gzip
    current_gzip=$(grep "gzip_comp_level " "$nginx_file" | awk '{print $2}' | sed 's/;//')
    NGINX_GZIP_COMP_LEVEL=${current_gzip:-4}
    
    # Need APP_DIR for create_nginx_config? 
    # The current create_nginx_config implementation uses APP_DIR only for a commented-out static block.
    # However, it might be safer to ensure it's set if possible, or accept empty if not used actively.
    # We can try to grab it from systemd file if available, or just leave it blank if not critical.
    # Let's try to get it from systemd as a fallback.
    local service_file="/etc/systemd/system/$APP_CODE_NAME.service"
    if [ -f "$service_file" ]; then
         APP_DIR=$(grep "^WorkingDirectory=" "$service_file" | cut -d= -f2-)
    fi

    # 2. Prompt for new values
    echo -e "${YELLOW}To keep the current/default value, just press Enter.${NC}\n"
    get_input "Enter the domain name" DOMAIN_NAME validate_domain_name \
        "Domain name for the application." "$DOMAIN_NAME"
        
    get_input "Enter NGINX gzip compression level (1-9)" NGINX_GZIP_COMP_LEVEL validate_integer \
        "Compression level." "$NGINX_GZIP_COMP_LEVEL"
        
    # We don't ask for APP_PORT here usually, as it's tied to the app service.
    # If the user changed the port in Systemd, they should update Nginx too.
    # Let's ask for it just in case, ensuring synchronization.
    get_input "Enter the internal app port" APP_PORT validate_port \
        "Port the Uvicorn app is running on (must match Systemd config)." "$APP_PORT"

    read -p "Do you want to apply these changes? (y/N): " APPLY_CHOICE
    if [[ "$APPLY_CHOICE" =~ ^[Yy]$ ]]; then
         # 3. Regenerate Config
         create_nginx_config # Uses DOMAIN_NAME, APP_PORT, NGINX_GZIP_COMP_LEVEL, APP_CODE_NAME
         
         echo -e "${GREEN}Nginx configuration updated and service reloaded.${NC}"
    else
         echo -e "${YELLOW}Changes discarded.${NC}"
    fi
}

reload_services() {
    echo -e "${YELLOW}1. Reloading Systemd Daemon...${NC}"
    sudo systemctl daemon-reload
    
    echo -e "${YELLOW}2. Restarting App Service ($APP_CODE_NAME)...${NC}"
    sudo systemctl restart "$APP_CODE_NAME"
    
    echo -e "${YELLOW}3. Reloading Nginx...${NC}"
    sudo systemctl reload nginx
    
    echo -e "${GREEN}All services reloaded.${NC}"
    
    # Show status
    echo -e "\n${CYAN}--- Service Status ---${NC}"
    sudo systemctl status "$APP_CODE_NAME" --no-pager | grep "Active:"
    sudo systemctl status nginx --no-pager | grep "Active:"
}
